apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sachinvashist/nextjs-docker:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-db

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100